# Configuración de Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.fwlmxodtpummrpyoorzm.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=xf7JLwKl4t4CnMcy

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

# Server
server.port=8080

# Opcional: Para desarrollo, puedes desactivar la validación de conexión
spring.datasource.hikari.initialization-fail-timeout=0